version: "3.5"
services:
  api: 
    build:
      context: ./api
      args:
        PORT: 8000
        HOST: "0.0.0.0"
    environment: 
      MONGO_DB: ${MONGO_DB}
      MONGO_HOST: ${MONGO_SVC}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on: 
      - mongo
    container-name: ${API_CONTAINER}
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./api:/usr/api
    networks:
      - api

  mongo:
    image: mongo:3.4.20-xenial
    restart: on-failure
    ports:
      - "${MONGO_PORT}:27017"
    container-name: ${MONGO_CONTAINER}
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB}"
    networks:
      - api

  mongo-express: 
    image: mongo-express:latest
    depends_on: 
      - mongo
    restart: on-failure
    container_name: ${MONGO_EXPRESS_CONTAINER}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
    networks:
      - api

networks: 
  api: 
    driver: bridge