from graphene import ObjectType, Int, String, Float, Boolean, ID, List

class Product(ObjectType):
    id = Int(required=True)
    barcode_number=String()
    barcode_type= String()
    barcode_formats= String()
    mpn=String()
    model = String()
    asin = String()
    product_name = String()
    title = String()
    category = String()
    manufacturer = String()
    brand = String()
    label = String()
    author = String()
    publisher = String()
    artist = String()
    actor = String()
    director = String()
    studio = String()
    genre = String()
    audience_rating = String()
    ingredients = String()
    nutrition_facts = String()
    format_ = String()
    package_quantity = Float(min=0)
    size = Float(min=0)
    length = Float(min=0)
    width = Float(min=0)
    height = Float(min=0)
    weight = Float(min=0)
    release_date = String()
    description = String()
    features = List(String)
    images = List(String)
# view-source:https://api.barcodelookup.com/v2/products?barcode=9780140157376&formatted=y&key=pw28iudadccdivcwtjae8j7580uadg
# https://api.barcodelookup.com/v2/products?barcode=3282779027540&formatted=y&key=pw28iudadccdivcwtjae8j7580uadg
